# Generated by Django 4.2.4 on 2023-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("intrest", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="preview",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recommendation",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
