# Generated by Django 5.0 on 2023-12-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrest', '0003_recommendation_preview_recommendation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
    ]
