# Generated by Django 5.0 on 2023-12-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intrest', '0004_recommendation_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='source',
            field=models.CharField(choices=[('books', 'books'), ('youtube', 'youtube')], default='books', max_length=20),
        ),
    ]
